### ISSUE TITLE
ADCJSCoreModule.m line 538 -[ADCJSCoreModule beginMessagePassing:]

### ISSUE THREAD

**Issue by robertodias180** [AdColony/AdColony-iOS-SDK-3#15]
I am getting this error on Version 3.0.6 

here is the crash log: http://crashes.to/s/08a39403480

any ideias?

edit:
in case the link expires here is the [log file](https://github.com/AdColony/AdColony-iOS-SDK-3/files/708063/com.creactive.millionnaire-gratuit_issue_1998_crash_3c2cee5ad57c4278a29f5cd43a500494_1d7c87cb511e4548adedb877a29143ff_0_v1.txt)

**Comment by cmanibog-ac** [comment]
Our team is has investigated this and the fix will be included in our 3.1 SDK update. This update is targeted for mid-February.

**Comment by ngoan** [comment]
@cmanibog-ac Any updates on this fix?

**Comment by cmanibog-ac** [comment]
Our GitHub has been updated with our 3.1 SDK. This crash is fixed in this version.

**Comment by alanchen** [comment]
I am using 3.1.1 but this issue still happens.
I think this issue is not fixed.
Please check again.
Thank you.

**Comment by cmanibog-ac** [comment]
Could you send a console log, with our v3.1.1 integrated, showing the app activity from when our SDK is initialized through the crash? For more streamlined communication, feel free to open a ticket with our support team for this at support@adcolony.com.

**Comment by guthyerrz** [comment]
@robertodias180 Hi Roberto, was the crash fixed when you updated? I'm also having this problem on 3.0.6 and I'm trying to decide if it's worth to update to 3.1.1.

**Comment by robertodias180** [comment]
@guthyerrz the new version fixed the issue for me.
