### ISSUE TITLE
Crash after video play [ADCContainer shouldAutorotate] is returning YES

### ISSUE THREAD

**Issue by lucamicheli** [AdColony/AdColony-iOS-SDK-3#9]
I've a Portrait app and after the video is played my app crash with this log:
Uncaught exception: Supported orientations has no common orientation with the application, and [ADCContainer shouldAutorotate] is returning YES

How can I solve?

**Comment by mwhite-ac** [comment]
We have tested a fix for this but don't have it available in the public repository yet.  Please send an email to support@adcolony.com and we'll provide you a link to get this update.  Note that this update is fully tested and not a beta version of the fix.

**Comment by owainm** [comment]
Fix is available in v3.0.6

**Comment by victorfigol** [comment]
@owainm 3.0.6 still has the same problem, tested with landscape app (left/right). After AdColony shows ad in portrait mode, the app will crash.

**Comment by lucasshrew** [comment]
Any news regarding this? I still have this issue in version 3.0.6.3

**Comment by gswati8** [comment]
Fix is available in v3.3. Please update to the latest SDK version

**Comment by lucamicheli** [comment]
I've updated to the 3.3 I still have the same problem.

<img width="545" alt="screen shot 2018-03-10 at 11 12 28" src="https://user-images.githubusercontent.com/700465/37241625-0672dbda-2454-11e8-9a15-7f7373983987.png">

Any help?

**Comment by cmanibog-ac** [comment]
@lucamicheli Unfortunately, our team was unable to reproduce this issue on 3.3. To look in to this further, could you share a repro of this on our sample app or share a sample .ipa reproducing this behavior? Are you building in Unity or using a mediation layer and if yes, which partner? Could you share a full console log showing the app activity from when our SDK is initialized through this display issue? 

Feel free to share this information through our support channel for direct communication with our Support/Engineering teams.

**Comment by happymark01** [comment]
https://github.com/AdColony/AdColony-iOS-SDK-3/issues/9#issuecomment-372490024
